baseURL = "https://datascience4biotech.com"
languageCode = "en-us"
title = "Data Science for Biotechnology"
theme = "hugo-theme-learn"
publishDir = "docs"
googleAnalytics = "UA-188880873-1"

[outputs]
home = ["HTML", "RSS", "JSON"]
